variables:
  imageName: windows-latest

pool:
  vmImage: $(imageName)

parameters:
  - name: getBaseLineResults
    default: false 
    type: boolean
  - name: setBaseLine
    default: false 
    type: boolean

stages: 
  - stage: SqlServer
    jobs: 
      
      - job: SqlServer 
        displayName: 'Deploy Azure SQL resource'
        steps: 
          - task: AzurePowerShell@5
            displayName: 'Deploy Azure SQL resource'
            inputs:
              azureSubscription: '<azureSubscription>'
              ScriptType: 'InlineScript'
              Inline: | 
                New-AzResourceGroupDeployment -TemplateFile $(System.DefaultWorkingDirectory)\src\modules\sqlserver-compliant.bicep `
                  -ResourceGroupName "<resourceGroupName>" `
                  -sqlServerName "<sqlServerName>" `
                  -administratorLogin "$(administratorLogin)" `
                  -administratorLoginPassword (ConvertTo-SecureString -AsPlainText -Force -String '$(administratorLoginPassword)')
              azurePowerShellVersion: 'LatestVersion'
  
  - stage: GetBaseLineResults
    condition: eq('${{ parameters.getBaseLineResults }}', true)
    jobs:
      
      - job: GetBaseLineResults
        displayName: 'Get baseline results' 
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '<azureSubscription>'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)\Scripts\Get-SqlBaselineInformation.ps1'
              ScriptArguments: >
                -SubscriptionId '<azureSubscriptionId>'
                -ResourceGroupName '<resourceGroupName>'
                -ServerName '<serverName>'
                -HelperModulePath '$(System.DefaultWorkingDirectory)\Scripts\SqlServerHelper.psm1'
                -OutputPath '$(Build.ArtifactStagingDirectory)'
              azurePowerShellVersion: 'LatestVersion'
      
          
          - task: PublishPipelineArtifact@1
            displayName: 'Publish baseline'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'Baseline'
              publishLocation: 'pipeline'
    
  - stage: SetBaseline
    condition: eq('${{ parameters.setBaseLine }}', true)
    jobs:
      
      - job: SetBaseline
        displayName: 'Set baseline' 
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: '<azureSubscription>'
              ScriptType: 'FilePath'
              ScriptPath: '$(System.DefaultWorkingDirectory)\Scripts\Set-SqlBaselineInformation.ps1'
              ScriptArguments: >
                -SubscriptionId ''<azureSubscriptionId>''
                -ResourceGroupName '<resourceGroupName>'
                -ServerName '<serverName>'
                -HelperModulePath '$(System.DefaultWorkingDirectory)\Scripts\SqlServerHelper.psm1'
                -BaseLinePath '$(System.DefaultWorkingDirectory)\Baselines'
              azurePowerShellVersion: 'LatestVersion'
        